configuration:
  snmp:
    community:
      authorization: read-only
      clients:
        - name: 10.255.127.20/32
        - name: 0.0.0.0/0
          restrict: null
      name: $home_snmp$
    interface: em0.0
    trap_group:
      categories:
        chassis: null
        routing: null
      name: SNMP_TRAP
      targets:
        name: 10.255.127.20
      version: v2
    trap_options:
      source_address:
        address: "{{ ansible_host }}"
