configuration:
  interfaces:
    apply_groups: GLOBAL_MTU_DEFAULTS
    interface:
      - name: xe-0/0/1
        description: linux server 1 (member of ae1)
        ether_options:
          ieee_802.3ad:
            bundle: ae1
      - name: xe-0/0/4
        description: 'POD1_SPINE2_LEAF4 (Member Of: ae4)'
        ether_options:
          ieee_802.3ad:
            bundle: ae4
      - name: xe-0/0/5
        description: 'POD1_SPINE1_LEAF4 (Member Of: ae5)'
        ether_options:
          ieee_802.3ad:
            bundle: ae5
      - name: xe-0/0/11
        unit:
          family:
            ethernet_switching:
              interface_mode: trunk
              vlan:
                members: all
          name: '0'
      - name: ae1
        aggregated_ether_options:
          lacp:
            active: null
            system_id: ae:02:11:00:00:00
        description: 'linux server 1 (Members: xe-0/0/1)'
        esi:
          all_active: null
          identifier: 00:ae:02:11:00:02:00:00:00:00
        unit:
          family:
            ethernet_switching:
              interface_mode: access
              vlan:
                members: '1048'
          name: '0'
      - name: ae4
        aggregated_ether_options:
          lacp:
            active: null
            periodic: fast
        description: POD1_SPINE2_LEAF4
        unit:
          family:
            inet:
              address:
                name: 10.2.2.7/31
            iso: null
          name: '0'
      - name: ae5
        aggregated_ether_options:
          lacp:
            active: null
            periodic: fast
        description: POD1_SPINE1_LEAF4
        unit:
          family:
            inet:
              address:
                name: 10.2.1.7/31
            iso: null
          name: '0'
      - name: em0
        unit:
          family:
            inet:
              address:
                name: 10.255.1.26/17
          name: '0'
      - name: em1
        unit:
          family:
            inet:
              address:
                name: 169.254.0.2/24
          name: '0'
      - name: lo0
        unit:
          - description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
              iso:
                address:
                  name: "{{ device.lo0.iso }}"
            name: "0"
