configuration:
  switch_options:
    route_distinguisher:
      rd_type: 192.168.255.10:999
    vrf_import: EVPN-IMPORT
    vrf_target:
      auto:
        import_as:
          name: '65000.101'
          vni_list: all
      community: target:999:999
    vtep_source_interface:
      interface_name: lo0.0
