---
- name: "### Upgrade software ###"
  hosts: all
  roles:
    - juniper.junos
  vars_files:
    - "shared/variables.yml"
    - "shared/secrets.yml"
  connection: local
  gather_facts: no
  tasks:
    ### -------------------------------------------------
    ### Software push and reboot
    ### -------------------------------------------------
    - name: upgrade OS
      juniper_junos_software:
        user: "{{ provider_info.user }}"
        # passwd: "{{ provider_info.passwd }}"
        ssh_private_key_file: "{{ provider_info.ssh_private_key_file }}"
        local_package: "./images/{{ device.software.os_image }}"
      register: response

    ### -------------------------------------------------
    ### Debug output
    ### -------------------------------------------------
    - name: Print the complete response.
      debug:
        var: response