configuration:
  protocols:
    evpn:
      default_gateway: no-gateway-community
      encapsulation: vxlan
      extended_vni_list: all
    igmp_snooping:
      vlan:
        - name: default
        - name: all
    isis:
      apply_groups: GLOBAL_ISIS_DEFAULTS
      interface:
        - name: ae0.0
        - name: ae2.0
        - name: ae4.0
        - name: ae5.0
        - name: lo0.0
          passive: null
    ldp:
      interface:
        - name: all
        - name: em0.0
          disable: null
      track_igp_metric: null
    lldp:
      interface:
        - name: all
        - name: em0
          disable: null
      port_id_subtype: interface-name
    lldp_med:
      interface:
        name: all
    mpls:
      interface:
        - name: all
        - name: em0.0
          disable: null
