---
- hosts: localhost
  gather_facts: False

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    image_name: hello-go
    replicas: 4

  tasks:
    - name: Scale Hello Go deployment with strategic merge.
      k8s:
        state: present
        merge_type: strategic-merge
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-go
            namespace: default
          spec:
            replicas: "{{ replicas }}"
