# Global config
global:
  scrape_interval:     2m
  evaluation_interval: 15s
  scrape_timeout: 100s
scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['localhost:9090']
  #
  #- job_name: 'node_exporter'
  #  static_configs:
  #    - targets: ['localhost:9100']
  #
  - job_name: 'junos_lan'
    static_configs:
      - targets: ['localhost:9326']